Create Database Customer_Behaviour;
Use Customer_Behaviour;
Select *
From Customer 
Limit 20;

-- Q1.What is the total revenue generated by male vs female customers?
	Select gender,sum(purchase_amount) as revenue
	From customer
	Group by gender;
    
-- Q2. Which customers used a discount but still spent more than the average purchase amount ?
Select customer_id,purchase_amount
From Customer 
where discount_applied='Yes' and purchase_amount>(Select Avg(purchase_amount)From customer);

-- Q3. Which are the top 5 products  with the highest average review rating ?
Select item_purchased,Round(Avg(review_rating),2) as "Average Product Rating"
From Customer
group by item_purchased
Order by Avg(review_rating) desc
Limit 5;

-- Q4. Compare the average Purchase Amount between  Standard  and Express Shipping
Select shipping_type,Round(Avg(purchase_amount),2)
From Customer 
where shipping_type in ('Express','Standard')
Group by shipping_type;

-- Q5. Do Subscribed  customers spend more? Compare average spend and total revenue between subscribers and non-subscribers
Select subscription_status,Count(customer_id) as total_customers,Round(Avg(purchase_amount),2) as avg_spend,Round(sum(purchase_amount),2) as total_revenue
From Customer
Group by subscription_status
Order by total_revenue,avg_spend desc;

-- Q6 . Which 5 Product have the highest percentage of purchases with discount applied?
Select item_purchased,Round(100 * sum(case when discount_applied="Yes" then 1 else 0 end )/count(*),2) as discount_rate
From customer 
Group by item_purchased
Order by discount_rate desc
Limit 5;

-- Q7. Segment customers into New ,Returning , and Loyal based on their total number of previous purchases, and show the count of  each segment
with customer_type as(
Select customer_id,previous_purchases,
Case
  when previous_purchases=1 then 'New' 
  When previous_purchases between 2 and 10  then 'Returning'
  else 'Loyal'
  End as customer_segment
From customer)

Select customer_segment,count(*) as "Number of customer"
from customer_type
group by customer_segment;

-- Q8. What are the top 3 most purchased products within each category?
With item_counts as (
Select category,item_purchased,count(customer_id) as total_orders,
Row_Number() over(
partition by category
Order by count(customer_id) desc
) as item_rank
From customer 
Group by category,item_purchased
)
Select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank<=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases ) also likely to subscribe?
Select subscription_status,count(customer_id) as repeat_buyers
from customer
where previous_purchases >5 
Group by  subscription_status;

-- Q10 . What is the revenue contribution of each age group ?
Select age_group , sum(purchase_amount) as total_revenue
from customer
group by age_group 
order by total_revenue desc;